import "./globals.css";
import { Poppins } from "next/font/google";
import { Providers } from "./providers";
import Sidebar from "@/components/Sidebar";
import Menubar from "@/components/Menubar";

export const metadata = {
  title: "Expense App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <Providers>
          <div className="">
            <div className=" fixed left-0 top-0 bottom-0 w-64 min-h-dvh border border-zinc-300 border-opacity-50 bg-zinc-200 border-r-2">
              <Sidebar />
            </div>
            <div className=" ml-64 flex flex-col h-full">
              <header className="pr-64 z-50 fixed top-0 w-full">
                <Menubar></Menubar>
              </header>
              <main className="overflow-y-auto mt-16 h-full">{children}</main>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
